baseURL: "https://www.gbsgroup.com.br/"
theme: "up-business-theme"
languageCode: "pt-BR"

title: ""

# googleAnalytics: ""

summaryLength: 20

params:
  title: "GBS"
  description: "Sua Visão, Nossa Tecnologia - GBS."
  images: 
    - "images/hero-image.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Limeira"

  contact:
    - "contato@gbsgroup.com.br"
    - "19 978135445"

  copyright: "© 2023 GBS Group All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Nossos Serviços"
      url: "#ourServices"
      weight: 2

    # - name: "Nosso Time"
    #   url: "/#"
    #   weight: 3

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

  buttons:
    - name: "Contato"
      url: "mailto:contato@gbsgroup.com.br?subject=Quero%20Crescer!"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Nossos Serviços"
      url: "#ourServices"
      weight: 2

    # - name: "Nosso Time"
    #   url: "/#"
    #   weight: 3

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

taxonomies:
  series: "series"
  tags: "tags"
