baseURL: "https://www.gbsgroup.com.br/"
theme: "up-business-theme"
languageCode: "pt-BR"

title: ""

# googleAnalytics: ""

summaryLength: 20

params:
  title: "GBS"
  description: "Somos bons."
  images: 
    - "images/hero-image.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Limeira"

  contact:
    - "contato@gbs-group.com.br"
    - "19 978135445"

  copyright: "© 2022 Up Business All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Como trabalhamos"
      url: "/#"
      weight: 2

    - name: "Nosso Time"
      url: "/#"
      weight: 3

    - name: "Preços"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Contato"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Como trabalhamos"
      url: "/#"
      weight: 2

    - name: "Nosso Time"
      url: "/#"
      weight: 3

    - name: "Preços"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
